version: '3'
services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - admin

  admin:
    build:
      context: ./admin
    ports:
      - "3001:3001"
